# -*- coding: utf-8 -*-
"""titanic_survival_Edward Jimenez

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMnkB0ZrsLzIsAfmAIDwfmkRkt7WYgK7

## CRISP-DM Step 1 and 2: Business and Data Understanding
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('titanic.csv')

# Display the first 5 rows to understand the data structure
print("First 5 rows of the dataset:")
display(df.head())

# Check for missing values
print("\nMissing values in each column:")
display(df.isnull().sum())

# Examine class balance of the target variable 'Survived'
print("\nClass balance of the 'Survived' target variable:")
display(df['Survived'].value_counts(normalize=True))

"""From the missing values check, we can see that there are no missing values in the dataset. The target variable 'Survived' shows an imbalance, with more passengers not surviving (0) than surviving (1).

## CRISP-DM Step 3: Data Preparation
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define feature matrix X and target vector y
X = df.drop('Survived', axis=1)
y = df['Survived']

# Drop 'Name' as it's not a useful feature for modeling
X = X.drop('Name', axis=1)

# Identify categorical and numerical features
categorical_features = ['Pclass', 'Sex']
numeric_features = ['Age', 'sibspouse', 'parentchild', 'Fare']

# Create preprocessing pipelines for numerical and categorical features
# Numerical features will be passed through without scaling as per instructions
numeric_transformer = Pipeline(steps=[('passthrough', 'passthrough')])

# Categorical features will be one-hot encoded
categorical_transformer = Pipeline(steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Perform a train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Data preparation complete. X_train, X_test, y_train, y_test are created.")
print(f"X_train shape: {X_train.shape}, X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}, y_test shape: {y_test.shape}")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define feature matrix X and target vector y
X = df.drop('Survived', axis=1)
y = df['Survived']

# Drop 'Name' as it's not a useful feature for modeling
X = X.drop('Name', axis=1)

# Identify categorical and numerical features
categorical_features = ['Pclass', 'Sex']
numeric_features = ['Age', 'sibspouse', 'parentchild', 'Fare']

# Create preprocessing pipelines for numerical and categorical features
# Numerical features will be passed through without scaling as per instructions
numeric_transformer = Pipeline(steps=[('passthrough', 'passthrough')])

# Categorical features will be one-hot encoded
categorical_transformer = Pipeline(steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Perform a train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Data preparation complete. X_train, X_test, y_train, y_test are created.")
print(f"X_train shape: {X_train.shape}, X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}, y_test shape: {y_test.shape}")

"""## CRISP-DM Step 4: Modeling"""

from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.4f}")
print(f"Model Precision: {precision:.4f}")
print(f"Model Recall: {recall:.4f}")

"""## CRISP-DM Step 5: Evaluation"""

from sklearn.linear_model import LogisticRegression

# Create the Logistic Regression model pipeline
# The preprocessor is already defined from the Data Preparation step
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(solver='liblinear', random_state=42))
])

# Fit the model on the training data
model.fit(X_train, y_train)

print("Logistic Regression model fitted successfully.")

# Generate predictions on the test set
y_pred = model.predict(X_test)
print("Predictions generated on the test set.")

"""## CRISP-DM Step 6: Deployment"""

import joblib

# Save the trained model
joblib.dump(model, 'titanic_survival_model.pkl')
print("Model saved as titanic_survival_model.pkl")

"""### Building the Streamlit Application

To deploy this model using Streamlit, you would typically create a new Python file (e.g., `app.py`) outside of this Colab notebook.

First, ensure you have Streamlit and Joblib installed in your environment:
"""

!pip install streamlit joblib

"""Below is a template for `app.py` that you can use. Remember to replace placeholder values and ensure the `titanic_survival_model.pkl` file is in the same directory as your `app.py` or provide the correct path.

To run the Streamlit app, save the following code as `app.py` and then execute `streamlit run app.py` in your terminal.
"""

import streamlit as st
import joblib
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load the trained model
try:
    model = joblib.load('titanic_survival_model.pkl')
except FileNotFoundError:
    st.error("Model file 'titanic_survival_model.pkl' not found. Please ensure it's in the same directory.")
    st.stop()

# Streamlit App Title
st.title('Titanic Survival Prediction')

st.write("Enter passenger details to predict survival.")

# Input fields for passenger features
pclass_options = {1: '1st Class', 2: '2nd Class', 3: '3rd Class'}
pclass_selection = st.selectbox('Passenger Class (Pclass)', options=list(pclass_options.keys()), format_func=lambda x: pclass_options[x])
sex_options = {'male': 'Male', 'female': 'Female'}
sex_selection = st.selectbox('Sex', options=list(sex_options.keys()), format_func=lambda x: sex_options[x])
age = st.slider('Age', 0, 80, 25)
sibspouse = st.slider('Number of Siblings/Spouses Aboard (sibspouse)', 0, 8, 0)
parentchild = st.slider('Number of Parents/Children Aboard (parentchild)', 0, 6, 0)
fare = st.number_input('Fare', min_value=0.0, value=30.0)

# Create a DataFrame from inputs
input_data = pd.DataFrame({
    'Pclass': [pclass_selection],
    'Sex': [sex_selection],
    'Age': [age],
    'sibspouse': [sibspouse],
    'parentchild': [parentchild],
    'Fare': [fare]
})

# Prediction
if st.button('Predict Survival'):
    prediction = model.predict(input_data)
    prediction_proba = model.predict_proba(input_data)

    st.subheader('Prediction Result:')
    if prediction[0] == 1:
        st.success(f'The passenger is predicted to **survive**! (Probability: {prediction_proba[0][1]*100:.2f}%)')
    else:
        st.error(f'The passenger is predicted to **not survive**. (Probability: {prediction_proba[0][0]*100:.2f}%)')

    st.write('---')
    st.write('Input Data:')
    st.dataframe(input_data)